export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_PENDING = 'GET_CLIENTS_PENDING';
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR';

export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS';
export const GET_PAYMENTS_PENDING = 'GET_PAYMENTS_PENDING';
export const GET_PAYMENTS_ERROR = 'GET_PAYMENTS_ERROR';

export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_PENDING = 'ADD_PAYMENT_PENDING';
export const ADD_PAYMENT_ERROR = 'ADD_PAYMENT_ERROR';

